{ pkgs, tauri-deps }:
let
  cerbo = pkgs.rustPlatform.buildRustPackage {
    pname = "cerbo";


    version = "0.1.0";
    src = ../.;
    cargoLock.lockFile = ../Cargo.lock;
    nativeBuildInputs = [ pkgs.pkg-config pkgs.mandown ];
    buildInputs = tauri-deps;
    # Network-dependent tests are #[ignore]d; the rest run in the sandbox.
    doCheck = true;

    # Install man page generated by build.rs from cli/man/cerbo.md via mandown.
    # Cargo puts build-script output under target/<triple>/release when a target
    # is set and target/release when it is not, so look in both.
    postInstall = ''
      mkdir -p $out/share/man/man1
      manPage=
      for dir in target/*/release/build/cerbo-*/out target/release/build/cerbo-*/out; do
        if [ -f "$dir/cerbo.1" ]; then
          manPage="$dir/cerbo.1"
          break
        fi
      done
      if [ -z "$manPage" ]; then
        echo "ERROR: cerbo.1 not found in build output (mandown should be available)" >&2
        exit 1
      fi
      cp "$manPage" $out/share/man/man1/
    '';
  };

  cerbo-frontend = pkgs.stdenv.mkDerivation {
    pname = "cerbo-frontend";


    version = "0.1.0";
    src = ../.;
    nativeBuildInputs = [
      pkgs.bun
      pkgs.bun2nix.hook
    ];
    bunDeps = pkgs.bun2nix.fetchBunDeps {
      bunNix = ./bun.nix;
      src = ../.;
    };
    buildPhase = ''
      bun install --no-save
      bun run build
    '';
    installPhase = ''
      mkdir -p $out
      cp -r build/* $out
    '';
  };

  cerbo-desktop = pkgs.rustPlatform.buildRustPackage {
    pname = "cerbo-desktop";


    version = "0.1.0";
    src = ../.;
    cargoLock.lockFile = ../Cargo.lock;
    buildAndTestFocus = "cerbo-desktop";
    nativeBuildInputs = [
      pkgs.pkg-config
      pkgs.wrapGAppsHook3
      pkgs.gobject-introspection
      pkgs.jq
    ];
    buildInputs = tauri-deps ++ [ pkgs.gtk3 pkgs.gsettings-desktop-schemas pkgs.adwaita-icon-theme ];

    postPatch = ''
      # Nullify devUrl and point frontendDist to the built frontend in the Nix store
      jq '.build.devUrl = null | .build.frontendDist = "${cerbo-frontend}"' src-tauri/tauri.conf.json > src-tauri/tauri.conf.json.tmp
      mv src-tauri/tauri.conf.json.tmp src-tauri/tauri.conf.json
    '';

    # Ensure Tauri doesn't try to use a dev server
    TAURI_ENV_DEBUG = "false";

    postInstall = ''
      rm -f $out/bin/cerbo

      # Install desktop file
      mkdir -p $out/share/applications
      cp src-tauri/cerbo-desktop.desktop $out/share/applications/

      # Install icons
      mkdir -p $out/share/icons/hicolor/scalable/apps
      cp src-tauri/icons/logo.svg $out/share/icons/hicolor/scalable/apps/cerbo-desktop.svg

      # Install fixed-size icons
      for size in 32 64 128; do
        mkdir -p $out/share/icons/hicolor/''${size}x''${size}/apps
        cp src-tauri/icons/''${size}x''${size}.png $out/share/icons/hicolor/''${size}x''${size}/apps/cerbo-desktop.png
      done
    '';
  };
in
{
  inherit cerbo cerbo-frontend cerbo-desktop;
}
